### ISSUE TITLE
Fonts rendering

### ISSUE THREAD

**Issue by hanshack** [svift-org/SVIFT-frontend#7]
add following fonts to renderer: Roboto+Mono:700|Patua+One|Noto+Serif:700

**Comment by sebastian-meier** [comment]
The fonts have been added. But you are using the Interface Font in the visualisations. The Interface Font is not coming from google but instead included in our frontend-package. We should only use typefaces from google or other free web-font-repos otherwise we need to host them. Right now the embeds are completely independent from our service, i would like to keep it that way. Can we use a google font for that?

**Comment by alsino** [comment]
Ok, all labels in the visualizations are now in 'Open Sans' (Google Font).

**Comment by sebastian-meier** [comment]
Open Sans > bold/italic > required?

Are those two fonts still in use: Merriweather|Poppins ? Otherwise i would remove them from the package.

**Comment by sebastian-meier** [comment]
Open Sans (700) is up and running on the dev machine.

**Comment by alsino** [comment]
We only need Open Sans (weight: 700) for the viz labels.  
Merriweather|Poppins are legacy and will not be missed. Ciao!
